# Generated by Django 3.2.3 on 2021-06-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_users_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='emaill',
        ),
    ]
