# Generated by Django 3.2.3 on 2021-06-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_email_users_emaill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='emaill',
        ),
    ]
