# Generated by Django 3.2.3 on 2021-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_users_emaill'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='emaill',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
