# Generated by Django 3.2.3 on 2021-06-02 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_users_emaill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kcal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kcal', models.IntegerField()),
                ('ea', models.IntegerField()),
                ('kcal_id', models.ForeignKey(db_column='kcal_id', on_delete=django.db.models.deletion.CASCADE, to='menu.menus')),
            ],
            options={
                'db_table': 'kcal',
            },
        ),
    ]
